FROM python:3.14

# Install required Python libraries
RUN pip install numpy pandas matplotlib

COPY . .
# Set the working directory
WORKDIR /workspace

# Copy the WDL script into the container
COPY . /workspace

# Set the entry point
ENTRYPOINT ["python3"]
